site_name: Open Data Hub - Highlander
site_url: https://odh-highlander.github.io/
repo_url: https://github.com/odh-highlander
edit_uri: https://github.com/odh-highlander/odh-highlander.github.io/tree/main/docs
theme: 
    name: material
    logo: img/highlander-logo.svg
    palette:
      - scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
        primary: blue
        accent: light blue
      - scheme: slate
        toggle:      
          icon: material/weather-sunny
          name: Switch to light mode
        primary: blue
        accent: light blue
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - navigation.indexes
        - navigation.top
        - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
    - Home: index.md
    - Introduction:
      - The problem: problem.md
      - The solution: solution.md
      - Highlander in action: action.md
    - Architecture: architecture.md
    - JupyterLab Extension:
      - Basic usage: jupyterlab-extension/basic-usage.md
      - Advanced functions: jupyterlab-extension/advanced-usage.md
